In [2]:
 import numpy as np

In [13]:
array = np.array([[1,2],[3,4]])

In [14]:
print (array)

[[1 2]
 [3 4]]


In [15]:
print (array.shape)

(2, 2)


In [16]:
num1 = [1,1,1,1,1]

In [17]:
num2 = [1,1,1,1,1]

In [18]:
num1 + num2

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [19]:
num3 = []
for i in range(len(num1)):
    num3.append(num1[i]+num2[i])
    

In [21]:
print(num3)

[2, 2, 2, 2, 2]


In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,3,4])

In [28]:
print(arr1 + arr2)

[2 5 7]


In [29]:
print(arr1 * arr2)

[ 1  6 12]


In [30]:
print(arr1 - arr2)

[ 0 -1 -1]


In [31]:
print(arr1 / arr2)

[1.         0.66666667 0.75      ]


In [32]:
print(arr1 + 5)

[6 7 8]
